service: graphql-lambda
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  graphql:
    handler: src/handler.graphqlHandler
    url:
      cors:
        allowedOrigins:
          - ${env:WEB_URL}
        allowedMethods:
          - GET
          - POST
        allowedHeaders:
          - Content-Type
          - Authorization

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
