service: graphql-lambda

frameworkVersion: '~4.19.1' # disable auto-updates, lock to this version

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}


functions:
  graphql:
    handler: src/handler.graphqlHandler
    url:
      cors:
        allowedOrigins:
          - https://d3fu52h97rrvnu.cloudfront.net
        allowedHeaders:
          - Content-Type
          - Authorization
        allowedMethods:
          - GET
          - POST
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000   # Default: 3000
