service: graphql-lambda

frameworkVersion: '~4.19.1' # disable auto-updates, lock to this version

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get

plugins:
  - serverless-offline
