service: graphql-lambda
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  graphql:
    handler: src/handler.graphqlHandler
    url:
      cors:
        allowedOrigins:
          - http://localhost:4000
          - https://d3fu52h97rrvnu.cloudfront.net
        allowedMethods:
          - GET
          - POST
        allowedHeaders:
          - Content-Type
          - Authorization
    events:   # local dev with API Gateway emulation
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
